/// Flutter icons MyFlutter
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutter
///      fonts:
///       - asset: fonts/MyFlutter.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutter {
  MyFlutter._();

  static const _kFontFam = 'MyFlutter';

  static const IconData calendar = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData youtube_play = const IconData(0xf16a, fontFamily: _kFontFam);
  static const IconData graduation_cap = const IconData(0xf19d, fontFamily: _kFontFam);
  static const IconData newspaper = const IconData(0xf1ea, fontFamily: _kFontFam);
  static const IconData chart_pie = const IconData(0xf200, fontFamily: _kFontFam);
  static const IconData chart_line = const IconData(0xf201, fontFamily: _kFontFam);
  static const IconData connectdevelop = const IconData(0xf20e, fontFamily: _kFontFam);
  static const IconData wikipedia_w = const IconData(0xf266, fontFamily: _kFontFam);
}
